### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by wei-steve** [shinyke/Time-NLP#3]
"下星期提醒我吃饭"
居然识别的时间是1970-1-1 0：0：0

**Comment by shinyke** [comment]
收到，待排查。谢谢反馈

**Comment by senlinxuefeng** [comment]
@shinyke 目前的代码有bug，楼主什么时候更新呢？

**Comment by shinyke** [comment]
@wei-steve @senlinxuefeng 
已修复，请更新。

谢谢反馈

**Comment by tangm00** [comment]
"本周日到下下周日提醒我晨跑"
本周日默认是下周日的时间：
2017-02-26 00:00:00-true
2017-03-05 00:00:00-true

**Comment by shinyke** [comment]
@tangm00 

已修复，谢谢反馈
