### ISSUE TITLE
“3小时后”这种Siri中常用的无法被识别，希望大大可以改进

### ISSUE THREAD

**Issue by wodelinglong** [shinyke/Time-NLP#35]

**Comment by xkzhangsan** [comment]
代码中没有相关功能，我正在自己的分支上添加支持时分秒功能。

**Comment by xkzhangsan** [comment]
在我的代码中已修复1小时后，1个半小时后，1小时50分钟等解析问题；并且支持到秒，比如50秒后，10分钟30秒后等。

**Comment by wodelinglong** [comment]
> 在我的代码中已修复1小时后，1个半小时后，1小时50分钟等解析问题；并且支持到秒，比如50秒后，10分钟30秒后等。

代码在哪里？没有找到

**Comment by xkzhangsan** [comment]
> > 在我的代码中已修复1小时后，1个半小时后，1小时50分钟等解析问题；并且支持到秒，比如50秒后，10分钟30秒后等。
> 
> 代码在哪里？没有找到

在 https://github.com/xkzhangsan/xk-time 中 https://github.com/xkzhangsan/xk-time/blob/master/src/main/java/com/xkzhangsan/time/nlp/TimeNLP.java

**Comment by xkzhangsan** [comment]
> > 在我的代码中已修复1小时后，1个半小时后，1小时50分钟等解析问题；并且支持到秒，比如50秒后，10分钟30秒后等。
> 
> 代码在哪里？没有找到

具体方法：com.xkzhangsan.time.nlp.TimeNLP#normBaseTimeRelated() 方法，同时需要增加正则表达式支持。
