### ISSUE TITLE
TimeExp读取问题

### ISSUE THREAD

**Issue by weiweiwang** [shinyke/Time-NLP#7]
String path = TimeNormalizer.class.getResource("").getPath();
		String classPath = path.substring(0, path.indexOf("/com/time"));
		System.out.println(classPath+"/TimeExp.m");
		TimeNormalizer normalizer = new TimeNormalizer(classPath+"/TimeExp.m");

如果将项目打成jar包加入到工程中，这种加载方式无法工作，因为jar中的资源是无法用FileInputStream读取的

**Comment by shinyke** [comment]
当前版本已解决，请更新。
